
# Set default number of threads to use
THREADS ?= 2

ifdef VERBOSE
	BATCH_VERBOSE := 1
	LIT_FLAGS := -v
else
	CMD_VERB ?= @
	NOPRINTD ?= --no-print-directory
	LIT_FLAGS ?= -sv
endif

ifdef LIT_THREADS
	LIT_FLAGS += --threads=$(LIT_THREADS)
endif

INTERNAL_CMAKE_OPTIONS :=

ifdef ELIB_CMAKE_OPTIONS
	INTERNAL_CMAKE_OPTIONS += $(ELIB_CMAKE_OPTIONS)
endif

# Configure the build type
ifdef BUILD
	INTERNAL_CMAKE_OPTIONS += -DCMAKE_BUILD_TYPE=$(BUILD)
endif

# Configure install prefix
ifdef PREFIX
	INTERNAL_CMAKE_OPTIONS += -DCMAKE_INSTALL_PREFIX=$(PREFIX)
endif

# Configuration for c++1y
ifdef CXX1Y
	INTERNAL_CMAKE_OPTIONS += -DCONFIG_CXX1Y=$(CXX1Y)
endif

# Turn experimental libraries on and off
ifdef ENABLE_EXPERIMENTAL
	INTERNAL_CMAKE_OPTIONS += -DCONFIG_ENABLE_EXPERIMENTAL=$(ENABLE_EXPERIMENTAL)
endif

# Configure asserting compiler/library configuration
ifdef ASSERT_CONFIG
	INTERNAL_CMAKE_OPTIONS += -DCONFIG_ELIB_ASSERT_CONFIG=$(ASSERT_CONFIG)
endif

# Configure building unit tests
ifdef UNIT_TESTS
	INTERNAL_CMAKE_OPTIONS += -DCONFIG_UNIT_TESTS=$(UNIT_TESTS)
endif

# Configure building header tests
ifdef HEADER_TESTS
	INTERNAL_CMAKE_OPTIONS += -DCONFIG_HEADER_TESTS=$(HEADER_TESTS)
endif

# Configure warnings used during build
ifdef ALL_WARNINGS
	INTERNAL_CMAKE_OPTIONS += -DCONFIG_ALL_WARNINGS=$(ALL_WARNINGS)
endif

ifdef PYTHON3
	INTERNAL_CMAKE_OPTIONS += -DCONFIG_PYTHON_3=$(PYTHON3)
endif