
# Set default number of threads to use
THREADS ?= 2

ifdef VERBOSE
	BATCH_VERBOSE := 1
	LIT_FLAGS := -v
else
	CMD_VERB ?= @
	NOPRINTD ?= --no-print-directory
	LIT_FLAGS ?= -sv
endif
	
# Configure the build type
ifdef BUILD
	ELIB_CMAKE_OPTIONS += -DCMAKE_BUILD_TYPE=$(BUILD)
endif

# Configure install prefix
ifdef PREFIX
	ELIB_CMAKE_OPTIONS += -DCMAKE_INSTALL_PREFIX=$(PREFIX)
endif

# Configuration for c++1y
ifdef CXX1Y
	ELIB_CMAKE_OPTIONS += -DCONFIG_CXX1Y=$(CXX1Y)
endif

# Turn experimental libraries on and off
ifdef ENABLE_EXPERIMENTAL
	ELIB_CMAKE_OPTIONS += -DCONFIG_ENABLE_EXPERIMENTAL=$(ENABLE_EXPERIMENTAL)
endif

# Configure asserting compiler/library configuration
ifdef ASSERT_CONFIG
	ELIB_CMAKE_OPTIONS += -DCONFIG_ELIB_ASSERT_CONFIG=$(ASSERT_CONFIG)
endif

# Configure building unit tests
ifdef UNIT_TESTS
	ELIB_CMAKE_OPTIONS += -DCONFIG_UNIT_TESTS=$(UNIT_TESTS)
endif

# Configure building header tests
ifdef HEADER_TESTS
	ELIB_CMAKE_OPTIONS += -DCONFIG_HEADER_TESTS=$(HEADER_TESTS)
endif

# Configure warnings used during build
ifdef ALL_WARNINGS
	ELIB_CMAKE_OPTIONS += -DCONFIG_ALL_WARNINGS=$(ALL_WARNINGS)
endif