#ifndef ELIB_CONFIG_COMPILER_MSVC_HPP
#define ELIB_CONFIG_COMPILER_MSVC_HPP
# 
# define ELIB_COMPILER MSVC
# define ELIB_COMPILER_VERSION 0
# define ELIB_CONFIG_MSVC 1
# 
#endif /* ELIB_CONFIG_COMPILER_MSVC_HPP */