################################################################################
set(LIT_EXECUTABLE "${ELIB_ROOT_PATH}/packages/lit/lit.py" 
    CACHE FILEPATH "Path to LLVM's lit.py.")

set(AUTO_GEN_COMMENT 
    "## Autogenerated by elib configuration.\n# Do not edit!")